services:
  postgres:
    image: postgres:18
    container_name: biblioteca
    restart: no
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-biblioteca}
    ports:
      - "${DB_PORT:-5440}:5432"
    volumes:
      - biblioteca_data:/var/lib/postgresql
      - ./dumps:/dumps

volumes:
  biblioteca_data: